-- 코드를 입력하세요
SELECT DISTINCT PRODUCT_CODE,  SUM(SALES_AMOUNT) * PRICE AS SALES
FROM OFFLINE_SALE  A
JOIN PRODUCT B
ON A.product_id = B.product_id
GROUP BY A.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC