# Generated by Django 3.2.18 on 2023-04-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Current_price', models.IntegerField()),
                ('Previous_rate', models.IntegerField()),
                ('Rate_of_change', models.TextField()),
                ('Face_value', models.IntegerField()),
                ('Market_capitalization', models.IntegerField()),
                ('listed_stock', models.IntegerField()),
                ('Foreigner_ratio', models.FloatField()),
                ('Trading_volume', models.TextField()),
                ('PER', models.FloatField()),
                ('ROE', models.FloatField()),
            ],
        ),
    ]
