-- 임시 테이블 
-- YEAR_DEV 테이블 만들기
WITH MAX_TABLE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

-- 

SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
ID
FROM ECOLI_DATA E
JOIN MAX_TABLE M
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC

