SELECT 
    B.TITLE, 
    B.BOARD_ID, 
    A.REPLY_ID, 
    A.WRITER_ID,
    A.CONTENTS,
    DATE_FORMAT(A.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM 
    USED_GOODS_BOARD B
JOIN 
    USED_GOODS_REPLY A
ON 
    B.BOARD_ID = A.BOARD_ID
WHERE 
    B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY 
    CREATED_DATE ASC, TITLE ASC